OperacoesAlunoTurma/OperacoesAlunoTurma/Models/AlunoModel.cs
using System.ComponentModel.DataAnnotations;

namespace OperacoesAlunoTurma.Models
{
    public class AlunoModel
    {
        public int Id { get; set; }        
        public string? Nome { get; set; }
        public string? Usuario { get; set; }
        public string? Senha { get; set; }
    }
}

OperacoesAlunoTurma/OperacoesAlunoTurma/Models/AlunoTurmaModel.cs
namespace OperacoesAlunoTurma.Models
{
    public class AlunoTurmaModel
    {
        public int AlunoId { get; set; }
        public int TurmaId { get; set; }

        // Propriedades de navegação

        public AlunoModel? Aluno { get; set; }
        public TurmaModel? Turma { get; set; } 
    }
}

OperacoesAlunoTurma/OperacoesAlunoTurma/Models/ErrorViewModel.cs
namespace OperacoesAlunoTurma.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OperacoesAlunoTurma/OperacoesAlunoTurma/Models/TurmaModel.cs
using System.ComponentModel.DataAnnotations;

namespace OperacoesAlunoTurma.Models
{
    public class TurmaModel
    {
        public int Id { get; set; }
        public int CursoId { get; set; }
        public string? Turma { get; set; }
        public int Ano { get; set; }
    }
}

OperacoesAlunoTurma/OperacoesAlunoTurma/Controllers/AlunoController.cs
using Microsoft.AspNetCore.Mvc;
using OperacoesAlunoTurma.Models;
using OperacoesAlunoTurma.Interfaces.Services;

namespace OperacoesAlunoTurma.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class AlunoController : Controller
    {
        private readonly IAlunoService _alunoService;

        public AlunoController(IAlunoService alunoService)
        {
            _alunoService = alunoService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var alunos = _alunoService.GetAll();
            return View(alunos);
        }

        //[HttpGet("create")]
        //public IActionResult Create()
        //{
        //    return View();
        //}

        [HttpPost]
        public IActionResult Create([FromForm] AlunoModel aluno)
        {
            if (!ModelState.IsValid)
            {
                return View(aluno);
            }

            _alunoService.Add(aluno);
            return RedirectToAction("Index");
        }

        [HttpGet("edit/{id}")]
        public IActionResult Edit([FromForm] int id)
        {
            var aluno = _alunoService.GetById(id);
            if (aluno == null)
                return NotFound();

            return View(aluno);
        }

        [HttpPut("{id}/edit")]
        public IActionResult Edit(int id, [FromForm] AlunoModel aluno)
        {
            if (id != aluno.Id || aluno == null | aluno.Id <= 0)
                return BadRequest(new { message = "Dados de aluno inválidos." });

            _alunoService.Update(aluno);
            return Json(new { message = "Atualização bem sucedida." });
        }

        [HttpPost("delete/{id}")]
        public IActionResult Delete(int id)
        {
            _alunoService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

OperacoesAlunoTurma/OperacoesAlunoTurma/Controllers/AlunoTurmaController.cs
using Microsoft.AspNetCore.Mvc;
using OperacoesAlunoTurma.Models;
using OperacoesAlunoTurma.Repositories;

namespace OperacoesAlunoTurma.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class AlunoTurmaController : Controller
    {
        private readonly AlunoTurmaRepository _alunoTurmaRepository;

        public AlunoTurmaController(AlunoTurmaRepository alunoTurmaRepository)
        {
            _alunoTurmaRepository = alunoTurmaRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var associacoes = _alunoTurmaRepository.GetAllAssociacoes();
            return View(associacoes);
        }

        [HttpGet("associate")]
        public IActionResult Associate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Associate(AlunoTurmaModel alunoTurma)
        {
            if (_alunoTurmaRepository.AssociacaoExiste(alunoTurma.AlunoId, alunoTurma.TurmaId))
            {
                ModelState.AddModelError("", "Associação já existe.");
                return View();
            }

            _alunoTurmaRepository.AddAssociacao(alunoTurma.AlunoId, alunoTurma.TurmaId);
            return RedirectToAction("Index");
        }

        [HttpDelete]
        public IActionResult Disassociate(int alunoId, int turmaId)
        {
            _alunoTurmaRepository.DeleteAssociacao(alunoId, turmaId);
            return RedirectToAction("Index");
        }

        [HttpGet("alunos/{alunoId}/turmas")]
        public IActionResult GetTurmasByAluno(int alunoId)
        {
            var turmas = _alunoTurmaRepository.GetTurmasByAluno(alunoId);
            return View(turmas);
        }

        [HttpGet("turmas/{turmaId}/alunos")]
        public IActionResult GetAlunosByTurma(int turmaId)
        {
            var alunos = _alunoTurmaRepository.GetAlunosByTurma(turmaId);
            return View(alunos);
        }
    }
}

OperacoesAlunoTurma/OperacoesAlunoTurma/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OperacoesAlunoTurma.Models;
using System.Diagnostics;

namespace OperacoesAlunoTurma.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OperacoesAlunoTurma/OperacoesAlunoTurma/Controllers/TurmaController.cs
using Microsoft.AspNetCore.Mvc;
using OperacoesAlunoTurma.Interfaces.Services;
using OperacoesAlunoTurma.Models;
using OperacoesAlunoTurma.Repositories;
using OperacoesAlunoTurma.Services;

namespace OperacoesAlunoTurma.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class TurmaController : Controller
    {
        private readonly ITurmaService _turmaService;

        public TurmaController(ITurmaService turmaService)
        {
            _turmaService = turmaService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var turmas = _turmaService.GetAll();
            return View(turmas);
        }

        //[HttpGet("create")]
        //public IActionResult Create()
        //{
        //    return View();
        //}

        [HttpPost]
        public IActionResult Create([FromForm] TurmaModel turma)
        {
            if (!ModelState.IsValid)
            {
                return View(turma);
            }

            _turmaService.Add(turma);
            return RedirectToAction("Index");
        }

        [HttpGet("{id}/edit")]
        public IActionResult Edit([FromForm] int id)
        {
            var turma = _turmaService.GetById(id);
            if (turma == null)
                return NotFound();

            return View(turma);
        }

        [HttpPut("{id}/edit")]
        public IActionResult Edit(int id, [FromForm] TurmaModel turma)
        {
            if (id != turma.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                _turmaService.Update(turma);
                return Json(new { message = "Atualização bem sucedida." });
            }

            return View(turma);
        }

        [HttpDelete("delete/{id}")]
        public IActionResult Delete(int id)
        {
            _turmaService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

OperacoesAlunoTurma/OperacoesAlunoTurma/Views/Aluno/Index.cshtml
@model IEnumerable<OperacoesAlunoTurma.Models.AlunoModel>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
@* <button type="button" id="editModalButton" class="btn btn-primary">
    Editar
</button> *@
<button type="button" id="createModalButton" class="btn btn-primary">
    Cadastrar Aluno
</button>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Senha)
            </th>
            <th>
                Ações
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Senha)
            </td>
            <td>
                <button type="button" id="editModalButton" class="btn btn-edit" data-id="@item.Id" data-nome="@item.Nome" data-usuario="@item.Usuario" data-senha="@item.Senha">
                    Editar
                </button>
                        <button type="button" class="btn-delete-direct" data-id="@item.Id">
                            Remover
                        </button>
                
            </td>
        </tr>
        }
    </tbody>
</table>
<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createModalLabel">Cadastrar Novo Aluno</h5>
                <button type="button" id="createModalCloseX" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" id="createForm" action="@Url.Action("Create", "Aluno")">
                    <div class="form-group">
                        <label for="createNome">Nome</label>
                        <input type="text" class="form-control" id="createNome" name="Nome" required />
                    </div>
                    <div class="form-group">
                        <label for="createUsuario">Usuário</label>
                        <input type="text" class="form-control" id="createUsuario" name="Usuario" required />
                    </div>
                    <div class="form-group">
                        <label for="createSenha">Senha</label>
                        <input type="text" class="form-control" id="createSenha" name="Senha" required />
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="createModalCloseButton" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Editar Aluno</h5>
                    <button type="button" id="editModalCloseX" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="editForm">
                    <input type="hidden" id="editId" name="Id" />
                    <div class="form-group">
                        <label for="editNome">Nome</label>
                        <input type="text" class="form-control" id="editNome" name="Nome">
                    </div>
                    <div class="form-group">
                        <label for="editUsuario">Usuario</label>
                        <input type="text" class="form-control" id="editUsuario" name="Usuario">
                    </div>
                    <div class="form-group">
                        <label for="editSenha">Senha</label>
                        <input type="text" class="form-control" id="editSenha" name="Senha">
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="editModalCloseButton" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
@* <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirmDelete">Delete</button>
            </div>
        </div>
    </div>
</div> *@

@section scripts {
    <script>
            $(document).ready(function () {
                $(".btn-edit").click(function () {
                    let id = $(this).data("id");
                    let nome = $(this).data("nome");
                    let usuario = $(this).data("usuario");
                    let senha = $(this).data("senha");

                    $("#editId").val(id);
                    $("#editNome").val(nome);
                    $("#editUsuario").val(usuario);
                    $("#editSenha").val(senha);

                    $("#editModal").modal('show');
                });

                $("#createForm, #editForm").submit(function (e) {
                    var passwordField;
                    var nomeField;
                    var usuarioField;

                    if ($(this).attr("id") === "createForm") {
                        passwordField = $(this).find("#createSenha");
                        nomeField = $(this).find("#createNome");
                        usuarioField = $(this).find("#createUsuario");
                    } else if ($(this).attr("id") === "editForm") {
                        passwordField = $(this).find("#editSenha");
                        nomeField = $(this).find("#editNome");
                        usuarioField = $(this).find("#editUsuario");
                    }

                    

                    var nome = nomeField.val();
                    var usuario = usuarioField.val();

                    if (nome.length > 255) {
                        alert("Nome deve ter no máximo 255 caracteres.")
                        e.preventDefault();
                        e.stopPropagation();
                        return;
                    }

                    if (usuario.length > 45) {
                        alert("Usuário deve ter no máximo 45 caracteres.")
                        e.preventDefault();
                        e.stopPropagation();
                        return;
                    }

                    var password = passwordField.val();
                    var regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@@$#&*{},=().+;'/!%^?\:|<>]).{12,60}$/;

                    if (!regex.test(password)) {
                        alert("Senha muito fraca. A senha deve possuir de 12 a 60 caracteres, pelo menos uma letra maiúscula e uma minúscula, um número e um caractere especial.");
                        e.preventDefault(); // Clear the input
                        e.stopPropagation();
                        return; // Exit out of the submit handler
                    }

                    // Only for editForm
                    if ($(this).attr("id") === "editForm") {
                        let formData = $(this).serialize();

                        $.ajax({
                            url: '/Aluno/Edit/' + $("#editId").val(),
                            type: 'Put',
                            data: formData,
                            success: function (response) {
                                location.reload();
                            },
                            error: function (error) {
                                alert("Erro ao atualizar o aluno.")
                            }
                        });

                        e.preventDefault(); // Ensure default form submission is prevented for AJAX
                    }
                });
            });
        $(document).ready(function () {
            $('#createModalButton').on('click', function () {
                $('#createModal').modal('show');
            });
        });
        $(document).ready(function () {
            $('#editModalButton').on('click', function () {
                $('#editModal').modal('show');
            });
        });
            $(document).ready(function () {
                $('.deleteModalButton').on('click', function () {
                    $('#deleteModal').modal('show');
                });
            });
        $(document).ready(function () {
            $('#editModalCloseX').on('click', function () {
                $('#editModal').modal('hide');
            });
        });
        $(document).ready(function () {
            $('#editModalCloseButton').on('click', function () {
                $('#editModal').modal('hide');
            });
        });
        $(document).ready(function () {
            $('#createModalCloseX').on('click', function () {
                $('#createModal').modal('hide');
            });
        });
        $(document).ready(function () {
            $('#createModalCloseButton').on('click', function () {
                $('#createModal').modal('hide');
            });
        });
        $(document).ready(function () {
            $(".btn-delete-direct").click(function () {
                let itemId = $(this).data("id");
                // $("#confirmDelete").attr("id", itemId);
                // $("#deleteModal").modal('show');

                    
                    console.log("Fetched ID:", itemId);

                if (!confirm("Tem certeza de que deseja deletar este item?")) {
                    return;
                }

                    let url = '/Aluno/Delete/' + itemId;
                    console.log("URL:", url);
                $.ajax({
                    url: '/Aluno/Delete/' + itemId,
                    type: 'Post',
                    success: function (response) {
                        location.reload();
                    },
                    error: function (error) {
                        alert("Failed to delete item.");
                    }
                });
            });
        });
    </script>
}
</body>
</html>

OperacoesAlunoTurma/OperacoesAlunoTurma/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OperacoesAlunoTurma/OperacoesAlunoTurma/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OperacoesAlunoTurma</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OperacoesAlunoTurma.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OperacoesAlunoTurma</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OperacoesAlunoTurma - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>